name: projectuasppb
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.10.3
  http: ^1.6.0
  image_picker: ^1.2.1
  flutter_secure_storage: ^9.2.4
  google_fonts: ^6.3.3
  flutter_riverpod: ^3.0.3
  intl: ^0.19.0
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1   

flutter_icons:                      
  android: true
  ios: false
  image_path: assets/icon/app_icon.png

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icon/app_icon.png       
